### Puxar base de dados

In [2]:
import pandas as pd

tabela = pd.read_csv("exportacoes_franca.csv")
display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

### Informações Gerais

In [6]:
print(tabela.info())

display(tabela.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  object
 3   City             142360 non-null  object
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  object
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  object
 8   Economic Block   142360 non-null  object
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), object(5)
memory usage: 11.9+ MB
None

,Year,Month,SH4 Code,SH2 Code,US$ FOB,Net Weight
count,142360.000000,142360.000000,142360.000000,142360.000000,1.423600e+05,1.423600e+05
mean,2018.065665,6.591922,6169.147246,61.516985,1.650039e+05,6.500505e+05
std,1.407972,3.462344,2655.071462,26.471381,1.247205e+06,9.875910e+06
min,2016.000000,1.000000,101.000000,1.000000,0.000000e+00,0.000000e+00
25%,2017.000000,4.000000,4009.000000,40.000000,4.170000e+02,3.000000e+00
50%,2018.000000,7.000000,7117.000000,71.000000,4.256500e+03,3.800000e+01
75%,2019.000000,10.000000,8483.000000,84.000000,3.710700e+04,3.185000e+03
max,2020.000000,12.000000,9999.000000,99.000000,1.086352e+08,7.100291e+08

### Como foi a evolução das exportações para a frança ao longo dos anos?

In [13]:
exportacao_ano = tabela.groupby("Year").sum()
exportacao_ano = exportacao_ano[["US$ FOB"]]

# criar uma função de formatação
def formatar(valor):
    return f"${valor:,.2f}"
# aplicar a formatação
exportacao_ano["US$ FOB"] = exportacao_ano["US$ FOB"].map(formatar)
display(exportacao_ano)

                US$ FOB
Year
2016  $4,615,500,082.00
2017  $4,448,705,456.00
2018  $5,239,424,416.00
2019  $5,218,723,612.00
2020  $3,967,594,810.00

### Quais os produtos mais exportados ao longo de todo o período?

In [17]:
exportacao_produto = tabela.groupby("SH4 Description").sum()
exportacao_produto = exportacao_produto[["US$ FOB"]]

exportacao_produto = exportacao_produto.sort_values('US$ FOB', ascending=False)

exportacao_produto["US$ FOB"] = exportacao_produto["US$ FOB"].map(formatar)
display(exportacao_produto)

                                                              US$ FOB
SH4 Description
Soybean oilcake and other solid residue, wh/not...  $5,628,424,640.00
Iron ores and concentrates, including roasted i...  $3,264,280,488.00
Chemical wood pulp, soda or sulphate, other tha...  $1,845,424,684.00
Coffee, whether or not roasted or decaffeinated...  $1,072,554,752.00
Other aircraft (for example, helicopters, aerop...    $685,133,070.00
...                                                               ...
Anti-freezing preparations and prepared de-icin...             $10.00
Man-made filament yarn (other than sewing threa...             $10.00
Glass envelopes (including bulbs and tubes), op...              $8.00
Cast glass and rolled glass, in sheets or profi...              $6.00
Drawing or colouring books for children                         $6.00

[935 rows x 1 columns]

### Em 2020 qual cidade mais exportou para a França?

In [21]:
tabela_2020 = tabela.loc[tabela["Year"]==2020, :]

exportacao_cidades_2020 = tabela_2020.groupby("City").sum()[["US$ FOB"]]
exportacao_cidades_2020 = exportacao_cidades_2020.sort_values('US$ FOB', ascending=False)


exportacao_cidades_2020["US$ FOB"] = exportacao_cidades_2020["US$ FOB"].map(formatar)
display(exportacao_cidades_2020)

                                     US$ FOB
City
Duque de Caxias - RJ         $279,405,596.00
Luís Eduardo Magalhães - BA  $265,328,132.00
Ponta Grossa - PR            $187,777,016.00
São José dos Campos - SP     $172,939,276.00
Rio de Janeiro - RJ          $122,522,214.00
...                                      ...
Não-Me-Toque - RS                     $42.00
Cubatão - SP                          $40.00
Holambra - SP                         $10.00
São Sebastião do Caí - RS              $6.00
Quatro Pontes - PR                     $0.00

[648 rows x 1 columns]

### O que as 2 maiores cidades exportaram tanto?

In [32]:
# Duque de Caxias
tabela_cidade = tabela_2020.loc[tabela_2020["City"]=="Duque de Caxias - RJ", :]
tabela_cidade = tabela_cidade.groupby("SH4 Description").sum()
tabela_cidade = tabela_cidade[["US$ FOB"]]
tabela_cidade = tabela_cidade.sort_values('US$ FOB', ascending=False)


tabela_cidade["US$ FOB"] = tabela_cidade["US$ FOB"].map(formatar)
display(tabela_cidade)

                                                            US$ FOB
SH4 Description
Turbo-jets, turbo-propellers and other gas turb...  $164,981,032.00
Crude oil from petroleum and bituminous minerals     $67,221,022.00
Transmission shafts (including cam shafts and c...    $9,795,392.00
Ball or roller bearings                               $8,247,090.00
Screws, bolts, nuts, coach screws, screw hooks,...    $4,218,846.00
Soybean oilcake and other solid residue, wh/not...    $4,014,274.00
Other articles of nickel                              $2,951,246.00
Other articles of iron or steel                       $2,847,128.00
Taps, cocks, valves and similar appliances for ...    $2,056,522.00
Articles of lead                                      $1,660,180.00
Tubes, pipes and hollow profiles, seamless, of ...    $1,477,752.00
Instruments and apparatus for measuring or chec...    $1,319,010.00
Automatic regulating or controlling instruments...    $1,132,774.00
Insulated (including enamelled or anodised) wir...      $904,248.00
Synthetic rubber and factice derived from oils,...      $825,818.00
Electrical ignition or starting equipment of a ...      $652,056.00
Other articles of vulcanised rubber other than ...      $553,478.00
Carboxyamide-function compounds; amide-function...      $535,136.00
Gaskets and similar joints of metal sheeting co...      $513,916.00
Tube or pipe fittings (for example, couplings, ...      $508,282.00
Electric sound or visual signalling apparatus (...      $465,606.00
Oscilloscopes, spectrum analysers and other ins...      $454,248.00
Motor cars and other motor vehicles principally...      $351,762.00
Electronic integrated circuits and microassemblies      $252,446.00
Electric motors and generators (excluding gener...      $229,426.00
Other articles of plastics and articles of othe...      $197,398.00
Other articles of aluminium                             $146,338.00
Centrifuges, including centrifugal dryers; filt...      $144,928.00
Petroleum oils and oils obtained from bituminou...      $134,666.00
Nails, tacks, drawing pins, staples (other than...      $117,988.00
Measuring or checking instruments, appliances a...      $101,720.00
Machinery, plant or laboratory equipment, wheth...       $76,986.00
Parts suitable for use solely or principally wi...       $66,906.00
Tubes, pipes and hollow profiles, of cast iron           $35,050.00
Hand tools (including glaziers' diamonds), not ...       $33,864.00
Springs and leaves for springs, of iron or steel         $24,662.00
Electrical apparatus for switching or protectin...       $24,360.00
Other articles of copper                                 $20,478.00
Accessories for tubes of aluminum                        $18,522.00
Worked mica and articles of mica, including agg...       $16,856.00
Other plates, sheets, film, foil and strip, of ...       $15,480.00
Other plates, sheets, film, foil and strip, of ...       $12,054.00
Artificial graphite; colloidal or semi-colloida...       $11,984.00
Articles of glass                                         $8,430.00
Stranded wire, ropes, cables, plaited bands, sl...        $5,454.00
Polymers of styrene, in primary forms                     $3,706.00
Orthopaedic appliances, including crutches, sur...        $3,684.00
Containers, including the fluid transport, spec...        $3,666.00
Aluminium tubes and pipes                                 $3,662.00
Trailers and semi-trailers; other vehicles, not...        $2,196.00
Revolution counters, production counters, taxim...        $1,656.00
Other tubes, pipes and hollow profiles (for exa...        $1,540.00
Other paper, paperboard, cellulose wadding and ...        $1,516.00
Pumps for liquids, whether or not fitted with a...        $1,116.00
Nickel bars, rods, profiles and wire                         $40.00